package org.jellerijk.minecraft.presenters;

import javafx.beans.property.IntegerProperty;
import javafx.beans.property.StringProperty;
import javafx.beans.value.ObservableIntegerValue;
import javafx.beans.value.ObservableStringValue;

public interface GeneratorViewModel {
    /**
     * Contains the Generator's name.
     */
    StringProperty nameProperty();

    /**
     *  Contains the amount of generators
     */
    IntegerProperty amountProperty();

    /**
     * Contains the su per unit of this generator.
     */
    IntegerProperty suPerUnitProperty();

    /**
     * Contains the total su generated by this group of generators.
     */
    IntegerProperty totalSuProperty();

    String getImagePath();


}
