package org.jellerijk.minecraft.viewModel;

import javafx.beans.property.IntegerProperty;
import javafx.beans.property.StringProperty;

public interface GeneratorEntryViewModel extends ComponentViewModel {
    /**
     * Contains the Generator's name.
     */
    StringProperty nameProperty();

    /**
     *  Contains the amount of generators
     */
    IntegerProperty amountProperty();

    /**
     * Contains the su per unit of this generator.
     */
    IntegerProperty suPerUnitProperty();

    /**
     * Contains the total su generated by this group of generators.
     */
    IntegerProperty totalSuProperty();

    String getImagePath();


}
